version "4.12"

//Check the README.md for info about reusing the code in "zscript_DI".

//base
#include "zscript_DI/parent.zsc"
#include "zscript_DI/mixin.zsc"

//eventhandlers
#include "zscript_DI/handlers/thebrain/main.zsc"
#include "zscript_DI/handlers/thebrain/override.zsc"
#include "zscript_DI/handlers/thebrain/wave.zsc"
#include "zscript_DI/handlers/thebrain/spawner.zsc"
#include "zscript_DI/handlers/thebrain/loot.zsc"
#include "zscript_DI/handlers/thebrain/monsters.zsc"
#include "zscript_DI/handlers/thebrain/supporters.zsc"
#include "zscript_DI/handlers/randomevent.zsc"
#include "zscript_DI/handlers/unlocker.zsc"
#include "zscript_DI/handlers/painter.zsc"
#include "zscript_DI/handlers/janitor.zsc"

//ZForms (uses MIT License)
#include "zscript_libraries/ZForms/Include.zsc"

//ui
#include "zscript_DI/ui/mixin.zsc"
#include "zscript_DI/ui/BoxHUD.zsc" //smh lazy dev copy/pasting code from their other game /s
#include "zscript_DI/ui/crosshair.zsc"
#include "zscript_DI/ui/itemhud.zsc"
#include "zscript_DI/ui/questhud.zsc"
#include "zscript_DI/ui/deathscreen.zsc"
#include "zscript_DI/ui/newgame/main.zsc"
#include "zscript_DI/ui/newgame/handler.zsc"
#include "zscript_DI/ui/newgame/tutorial.zsc"
#include "zscript_DI/ui/newgame/player.zsc"
#include "zscript_DI/ui/newgame/level.zsc"
#include "zscript_DI/ui/newgame/skill.zsc"
#include "zscript_DI/ui/catalogue/menu.zsc"
#include "zscript_DI/ui/catalogue/handler.zsc"
#include "zscript_DI/ui/unlock/menu.zsc"
#include "zscript_DI/ui/unlock/handler.zsc"
#include "zscript_DI/ui/unused/MainMenu.zsc"

//decoration
#include "zscript_DI/decoration/painting.zsc"
#include "zscript_DI/decoration/beam.zsc"
#include "zscript_DI/decoration/glass.zsc"
#include "zscript_DI/decoration/tree.zsc"
#include "zscript_DI/decoration/foliage.zsc"
#include "zscript_DI/decoration/fakewindow.zsc"
#include "zscript_DI/decoration/smoker.zsc"
#include "zscript_DI/decoration/jumppad.zsc"
#include "zscript_DI/decoration/lantern.zsc"
#include "zscript_DI/decoration/background.zsc"

//effects
#include "zscript_DI/effects/blood.zsc"
#include "zscript_DI/effects/gib.zsc"
#include "zscript_DI/effects/puff.zsc"
#include "zscript_DI/effects/trail.zsc"
#include "zscript_DI/effects/teleport.zsc"
#include "zscript_DI/effects/spawner.zsc"
#include "zscript_DI/effects/marker.zsc"
#include "zscript_DI/effects/boom.zsc"
#include "zscript_DI/effects/deathbullet.zsc"
#include "zscript_DI/effects/canvas.zsc"
#include "zscript_DI/effects/casings.zsc"
#include "zscript_DI/effects/splashes.zsc"
#include "zscript_DI/effects/walltrap.zsc"
#include "zscript_DI/effects/stalactite.zsc"
#include "zscript_DI/effects/shadow.zsc"
#include "zscript_DI/effects/skybox.zsc"

//player
#include "zscript_DI/player/base.zsc"
#include "zscript_DI/player/fredrick.zsc"
#include "zscript_DI/player/box.zsc"
#include "zscript_DI/player/burger.zsc"
#include "zscript_DI/player/hamill.zsc"

//pickups
#include "zscript_DI/pickups/base.zsc"
#include "zscript_DI/pickups/coin.zsc"
#include "zscript_DI/pickups/flash.zsc"
#include "zscript_DI/pickups/bag.zsc"

//items
#include "zscript_DI/items/mixin.zsc"
#include "zscript_DI/items/base.zsc"
#include "zscript_DI/items/health.zsc"
#include "zscript_DI/items/armor.zsc"
#include "zscript_DI/items/quest.zsc"
//debuffs
#include "zscript_DI/items/debuffs/slow.zsc"
#include "zscript_DI/items/debuffs/defenseless.zsc"
#include "zscript_DI/items/debuffs/tornpockets.zsc"
#include "zscript_DI/items/debuffs/encumbered.zsc"
//objectives
#include "zscript_DI/items/objectives/fresh.zsc"
#include "zscript_DI/items/objectives/blooddrive.zsc"
#include "zscript_DI/items/objectives/sleightofhand.zsc"
#include "zscript_DI/items/objectives/overconsumption.zsc"
#include "zscript_DI/items/objectives/kill_bigmelon.zsc"
//passive items
#include "zscript_DI/items/passives/fakestatups.zsc"
#include "zscript_DI/items/passives/statups.zsc"
#include "zscript_DI/items/passives/bloodyheart.zsc"
#include "zscript_DI/items/passives/bonusarmor.zsc"
#include "zscript_DI/items/passives/hathat.zsc"
#include "zscript_DI/items/passives/status.zsc"
#include "zscript_DI/items/passives/freshregen.zsc"
#include "zscript_DI/items/passives/shoe.zsc"
#include "zscript_DI/items/passives/wealthjar.zsc"
#include "zscript_DI/items/passives/consumer.zsc"
#include "zscript_DI/items/passives/leadrecycling.zsc"
#include "zscript_DI/items/passives/peerpressure.zsc"
#include "zscript_DI/items/passives/acidblood.zsc"
#include "zscript_DI/items/passives/freshbullets.zsc"
#include "zscript_DI/items/passives/firestarter.zsc"
#include "zscript_DI/items/passives/laststand.zsc"
#include "zscript_DI/items/passives/creditfraud.zsc"
#include "zscript_DI/items/passives/leadswitch.zsc"
#include "zscript_DI/items/passives/markedfordeath.zsc"
#include "zscript_DI/items/passives/coinmagnet.zsc"
#include "zscript_DI/items/passives/farsight.zsc"
#include "zscript_DI/items/passives/toaster.zsc"
//consumable items
#include "zscript_DI/items/consumables/health.zsc"
#include "zscript_DI/items/consumables/bomb.zsc"
#include "zscript_DI/items/consumables/heartbomb.zsc"
#include "zscript_DI/items/consumables/turret.zsc"
#include "zscript_DI/items/consumables/reroll.zsc"
#include "zscript_DI/items/consumables/tomahawk.zsc"
#include "zscript_DI/items/consumables/ammosatchel.zsc"
#include "zscript_DI/items/consumables/brick.zsc"
#include "zscript_DI/items/consumables/9leafclover.zsc"
#include "zscript_DI/items/consumables/fastforward.zsc"

//weapons
#include "zscript_DI/weapons/base.zsc" //not a weapon
#include "zscript_DI/weapons/bullet.zsc" //not a weapon
#include "zscript_DI/weapons/mixin.zsc" //not a weapon
//starting weapons
#include "zscript_DI/weapons/starter/starpistol.zsc"
#include "zscript_DI/weapons/starter/glowstick.zsc"
#include "zscript_DI/weapons/starter/cheesegun.zsc"
#include "zscript_DI/weapons/starter/sledgehammer.zsc"
//#include "zscript_DI/weapons/starter/poisoner.zsc"
//basic weapons
#include "zscript_DI/weapons/basic/greenshotgun.zsc"
#include "zscript_DI/weapons/basic/bluesmg.zsc"
#include "zscript_DI/weapons/basic/pinkrifle.zsc"
//normal weapons
#include "zscript_DI/weapons/normal/grenadelauncher.zsc"
//#include "zscript_DI/weapons/normal/sniperrifle.zsc"
//#include "zscript_DI/weapons/normal/dualsmg.zsc"
#include "zscript_DI/weapons/normal/doubleshotgun.zsc"
//fantasy weapons
#include "zscript_DI/weapons/fantasy/stunbow.zsc"
//#include "zscript_DI/weapons/fantasy/swordshield.zsc"
//#include "zscript_DI/weapons/fantasy/magicstaff.zsc"
//#include "zscript_DI/wepaons/fantasy/cards.zsc"
//sci-fi weapons
//#include "zscript_DI/weapons/scifi/plasmapistol.zsc"
//#include "zscript_DI/weapons/scifi/plasmarifle.zsc"
//#include "zscript_DI/weapons/scifi/railgun.zsc"
//super weapons
//#include "zscript_DI/weapons/super/flamethrower.zsc"
//#include "zscript_DI/weapons/super/missilelauncher.zsc"
//#include "zscript_DI/weapons/super/minigun.zsc"
//#include "zscript_DI/weapons/super/boomshotgun.zsc"
//#include "zscript_DI/weapons/super/thebigone.zsc"
//box party weapons
#include "zscript_DI/weapons/box/boxammo.zsc" //not a weapon
#include "zscript_DI/weapons/box/laserpointer.zsc"
#include "zscript_DI/weapons/box/partyshotty.zsc"
#include "zscript_DI/weapons/box/popcorngun.zsc"
//#include "zscript_DI/weapons/box/partyshotty2.zsc" //not actually used in box party

//enemies
#include "zscript_DI/enemies/monster.zsc"
#include "zscript_DI/enemies/boss.zsc"
#include "zscript_DI/enemies/bullet.zsc"
#include "zscript_DI/enemies/mixin.zsc"
#include "zscript_DI/enemies/randomspawner.zsc"
#include "zscript_DI/enemies/basic/fred.zsc"
#include "zscript_DI/enemies/basic/ron.zsc"
#include "zscript_DI/enemies/box/fruitpuncher.zsc"
#include "zscript_DI/enemies/box/THEHAMMER.zsc"
#include "zscript_DI/enemies/box/pepper.zsc"
#include "zscript_DI/enemies/box/onion.zsc"
#include "zscript_DI/enemies/box/redonion.zsc"
#include "zscript_DI/enemies/box/bigpizza.zsc"
#include "zscript_DI/enemies/box/smallpizza.zsc"
#include "zscript_DI/enemies/box/lemon.zsc"
#include "zscript_DI/enemies/special/debtcollector.zsc"
#include "zscript_DI/enemies/special/bigmelon.zsc"

//shop
#include "zscript_DI/shop/base.zsc" //base actor all shop-type actors inherit from
#include "zscript_DI/shop/shop.zsc" //actual shops
#include "zscript_DI/shop/controller.zsc" //fake shops that run some kinda script
#include "zscript_DI/shop/display.zsc" //item sprites and prices displayed over the shops
#include "zscript_DI/shop/ghostshop.zsc" //does nothing. used to represent where the next shops will spawn.
#include "zscript_DI/shop/chest.zsc" //can provide 1 random perma item per round. price never goes down.
#include "zscript_DI/shop/questgiver.zsc" //gives the player quests.

//secret (shh don't tell anyone ok???)
#include "zscript_DI/secret/cats.zsc"

//aim assist mod
#include "zscript_libraries/AimAssist/Handler.zs"
#include "zscript_libraries/AimAssist/PlayerData.zs"
#include "zscript_libraries/AimAssist/Marker.zs"
#include "zscript_libraries/AimAssist/Menu.zs"
#include "zscript_libraries/AimAssist/ZJSON/Include.zs"

//precise crosshair mod
#include "zscript_libraries/precisecrosshair/pc_event_handler.zs"
#include "zscript_libraries/precisecrosshair/pc_puff.zs"
#include "zscript_libraries/precisecrosshair/libeye/pc_projector.zs"
#include "zscript_libraries/precisecrosshair/libeye/pc_projector gl.zs"
#include "zscript_libraries/precisecrosshair/libeye/pc_projector planar.zs"
#include "zscript_libraries/precisecrosshair/libeye/pc_viewport.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_settings_base.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_cvar_setting.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_bool_setting.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_settings_pack.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_settings.zs"

//weapon speed scaling
#include "zscript_libraries/speedscale/psprite-speed-scaler.zc"

//////////////////////////////////////////////////////////////
//The below included code is under the MIT License.
//You can find the details either embedded in the file itself,
//or inside the same folder as the file.
//////////////////////////////////////////////////////////////

//libtooltipmenu
#include "zscript_libraries/libtooltipmenu/Tooltips.zsc"
#include "zscript_libraries/libtooltipmenu/TooltipOptionMenu.zsc"
#include "zscript_libraries/libtooltipmenu/TooltipListMenu.zsc"

//nashhpbar
#include "zscript_libraries/NashHPBar/NashHPBarOptionMenu/NashHPBarOptionMenu.zsc"
#include "zscript_libraries/NashHPBar/NashHPBarPlugin/NashHPBarPlugin.zsc"
#include "zscript_libraries/NashHPBar/NashHPBarHandler/NashHPBarHandler.zsc"

//damnums
#include "zscript_libraries/damnums/constants.txt"
#include "zscript_libraries/damnums/damnum.txt"
#include "zscript_libraries/damnums/events.txt"
#include "zscript_libraries/damnums/fonts/base.txt"
#include "zscript_libraries/damnums/fonts/borderlands.txt"
#include "zscript_libraries/damnums/fonts/gamedefaults.txt"