version "4.11"

//Check the README.md for info about reusing the code in "zscript_DI".

//base
#include "zscript_DI/parent.zsc"
#include "zscript_DI/mixin.zsc"

//eventhandlers
#include "zscript_DI/handlers/main.zsc"
#include "zscript_DI/handlers/main/override.zsc"
#include "zscript_DI/handlers/main/wave.zsc"
#include "zscript_DI/handlers/main/spawner.zsc"
#include "zscript_DI/handlers/main/loot.zsc"
#include "zscript_DI/handlers/main/monsters.zsc"
#include "zscript_DI/handlers/main/floor.zsc"
#include "zscript_DI/handlers/randomevent.zsc"
#include "zscript_DI/handlers/crosshair.zsc"
#include "zscript_DI/handlers/hattrack.zsc"
#include "zscript_DI/handlers/itemhud.zsc"
#include "zscript_DI/handlers/deathscreen.zsc"
#include "zscript_DI/handlers/painter.zsc"

//ZForms (uses MIT License)
#include "zscript_libraries/ZForms/Include.zsc"

//boxhats (uses MIT License)
#include "zscript_libraries/boxhats/spawnhandler.zsc"
#include "zscript_libraries/boxhats/menuhandler.zsc"
#include "zscript_libraries/boxhats/hatmenu.zsc"
#include "zscript_libraries/boxhats/hat.zsc"
#include "zscript_libraries/boxhats/hatdummy.zsc"

//ui
#include "zscript_DI/ui/MainMenu.zsc"
#include "zscript_DI/ui/NewGame.zsc"
#include "zscript_DI/ui/newgame/Handler.zsc"
#include "zscript_DI/ui/newgame/Tutorial.zsc"
#include "zscript_DI/ui/newgame/Player.zsc"
#include "zscript_DI/ui/newgame/Level.zsc"
#include "zscript_DI/ui/newgame/Skill.zsc"
#include "zscript_DI/ui/BoxHUD.zsc" //smh lazy dev copy/pasting code from their other game /s
#include "zscript_DI/ui/Catalogue.zsc"
#include "zscript_DI/ui/CatalogueHandler.zsc"

//decoration
#include "zscript_DI/decoration/painting.zsc"
#include "zscript_DI/decoration/beam.zsc"
#include "zscript_DI/decoration/glass.zsc"
#include "zscript_DI/decoration/tree.zsc"
#include "zscript_DI/decoration/foliage.zsc"

//effects
#include "zscript_DI/effects/blood.zsc"
#include "zscript_DI/effects/gib.zsc"
#include "zscript_DI/effects/puff.zsc"
#include "zscript_DI/effects/trail.zsc"
#include "zscript_DI/effects/teleport.zsc"
#include "zscript_DI/effects/spawner.zsc"
#include "zscript_DI/effects/marker.zsc"
#include "zscript_DI/effects/boom.zsc"
#include "zscript_DI/effects/deathbullet.zsc"
#include "zscript_DI/effects/canvas.zsc"
#include "zscript_DI/effects/casings.zsc"
#include "zscript_DI/effects/splashes.zsc"

//player
#include "zscript_DI/player/base.zsc"
#include "zscript_DI/player/fredrick.zsc"
#include "zscript_DI/player/box.zsc"
#include "zscript_DI/player/burger.zsc"

//pickups
#include "zscript_DI/pickups/base.zsc"
#include "zscript_DI/pickups/coin.zsc"
#include "zscript_DI/pickups/flash.zsc"

//items
#include "zscript_DI/items/mixin.zsc"
#include "zscript_DI/items/base.zsc"
#include "zscript_DI/items/health.zsc"
#include "zscript_DI/items/armor.zsc"
//passive items
#include "zscript_DI/items/passives/fakestatups.zsc"
#include "zscript_DI/items/passives/statups.zsc"
#include "zscript_DI/items/passives/bloodyheart.zsc"
#include "zscript_DI/items/passives/bonusarmor.zsc"
#include "zscript_DI/items/passives/hathat.zsc"
#include "zscript_DI/items/passives/status.zsc"
#include "zscript_DI/items/passives/freshregen.zsc"
#include "zscript_DI/items/passives/shoe.zsc"
#include "zscript_DI/items/passives/wealthjar.zsc"
#include "zscript_DI/items/passives/consumer.zsc"
#include "zscript_DI/items/passives/leadrecycling.zsc"
#include "zscript_DI/items/passives/peerpressure.zsc"
#include "zscript_DI/items/passives/acidblood.zsc"
#include "zscript_DI/items/passives/freshbullets.zsc"
#include "zscript_DI/items/passives/firestarter.zsc"
#include "zscript_DI/items/passives/laststand.zsc"
#include "zscript_DI/items/passives/creditfraud.zsc"
#include "zscript_DI/items/passives/leadswitch.zsc"
//consumable items
#include "zscript_DI/items/consumables/health.zsc"
#include "zscript_DI/items/consumables/bomb.zsc"
#include "zscript_DI/items/consumables/heartbomb.zsc"
#include "zscript_DI/items/consumables/turret.zsc"
#include "zscript_DI/items/consumables/reroll.zsc"
#include "zscript_DI/items/consumables/tomahawk.zsc"
#include "zscript_DI/items/consumables/ammosatchel.zsc"
#include "zscript_DI/items/consumables/brick.zsc"
#include "zscript_DI/items/consumables/9leafclover.zsc"

//weapons
#include "zscript_DI/weapons/base.zsc" //not a weapon
#include "zscript_DI/weapons/bullet.zsc" //not a weapon
#include "zscript_DI/weapons/mixin.zsc" //not a weapon
//starting weapons
#include "zscript_DI/weapons/starter/starpistol.zsc"
#include "zscript_DI/weapons/starter/glowstick.zsc"
#include "zscript_DI/weapons/starter/cheesegun.zsc"
//#include "zscript_DI/weapons/starter/poisoner.zsc"
//basic weapons
#include "zscript_DI/weapons/basic/greenshotgun.zsc"
#include "zscript_DI/weapons/basic/bluesmg.zsc"
#include "zscript_DI/weapons/basic/pinkrifle.zsc"
//normal weapons
#include "zscript_DI/weapons/normal/grenadelauncher.zsc"
//#include "zscript_DI/weapons/normal/sniperrifle.zsc"
//#include "zscript_DI/weapons/normal/dualsmg.zsc"
#include "zscript_DI/weapons/normal/doubleshotgun.zsc"
//fantasy weapons
#include "zscript_DI/weapons/fantasy/stunbow.zsc"
//#include "zscript_DI/weapons/fantasy/swordshield.zsc"
//#include "zscript_DI/weapons/fantasy/magicstaff.zsc"
//#include "zscript_DI/wepaons/fantasy/cards.zsc"
//sci-fi weapons
//#include "zscript_DI/weapons/scifi/plasmapistol.zsc"
//#include "zscript_DI/weapons/scifi/plasmarifle.zsc"
//#include "zscript_DI/weapons/scifi/railgun.zsc"
//super weapons
//#include "zscript_DI/weapons/super/flamethrower.zsc"
//#include "zscript_DI/weapons/super/missilelauncher.zsc"
//#include "zscript_DI/weapons/super/minigun.zsc"
//#include "zscript_DI/weapons/super/boomshotgun.zsc"
//#include "zscript_DI/weapons/super/thebigone.zsc"
//box party weapons
#include "zscript_DI/weapons/box/boxammo.zsc" //not a weapon
#include "zscript_DI/weapons/box/laserpointer.zsc"
#include "zscript_DI/weapons/box/partyshotty.zsc"
#include "zscript_DI/weapons/box/popcorngun.zsc"
#include "zscript_DI/weapons/box/partyshotty2.zsc" //not actually used in box party
//#include "zscript_DI/weapons/box/sledgehammer.zsc" //not actually used in box party

//enemies
#include "zscript_DI/enemies/monster.zsc"
#include "zscript_DI/enemies/bullet.zsc"
#include "zscript_DI/enemies/mixin.zsc"
#include "zscript_DI/enemies/randomspawner.zsc"
#include "zscript_DI/enemies/basic/fred.zsc"
#include "zscript_DI/enemies/basic/ron.zsc"
#include "zscript_DI/enemies/box/fruitpuncher.zsc"
#include "zscript_DI/enemies/special/debtcollector.zsc"

//shop
#include "zscript_DI/shop/base.zsc" //base actor all shop-type actors inherit from
#include "zscript_DI/shop/shop.zsc" //actual shops
#include "zscript_DI/shop/controller.zsc" //fake shops that run some kinda script
#include "zscript_DI/shop/display.zsc" //item sprites and prices displayed over the shops
#include "zscript_DI/shop/ghostshop.zsc" //does nothing. used to represent where the next shops will spawn.
#include "zscript_DI/shop/chest.zsc" //can provide 1 random perma item per round. price never goes down.

//secret (shh don't tell anyone ok???)
#include "zscript_DI/secret/cats.zsc"

//aim assist mod
#include "zscript_libraries/AimAssist/Handler.zs"
#include "zscript_libraries/AimAssist/PlayerData.zs"
#include "zscript_libraries/AimAssist/Marker.zs"
#include "zscript_libraries/AimAssist/Menu.zs"
#include "zscript_libraries/AimAssist/ZJSON/Include.zs"

//precise crosshair mod
#include "zscript_libraries/precisecrosshair/pc_event_handler.zs"
#include "zscript_libraries/precisecrosshair/pc_puff.zs"
#include "zscript_libraries/precisecrosshair/libeye/pc_projector.zs"
#include "zscript_libraries/precisecrosshair/libeye/pc_projector gl.zs"
#include "zscript_libraries/precisecrosshair/libeye/pc_projector planar.zs"
#include "zscript_libraries/precisecrosshair/libeye/pc_viewport.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_settings_base.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_cvar_setting.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_bool_setting.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_settings_pack.zs"
#include "zscript_libraries/precisecrosshair/settings/pc_settings.zs"

//////////////////////////////////////////////////////////////
//The below included code is under the MIT License.
//You can find the details either embedded in the file itself,
//or inside the same folder as the file.
//////////////////////////////////////////////////////////////

//libtooltipmenu
#include "zscript_libraries/libtooltipmenu/Tooltips.zsc"
#include "zscript_libraries/libtooltipmenu/TooltipOptionMenu.zsc"
#include "zscript_libraries/libtooltipmenu/TooltipListMenu.zsc"

//nashhpbar
#include "zscript_libraries/NashHPBar/NashHPBarOptionMenu/NashHPBarOptionMenu.zsc"
#include "zscript_libraries/NashHPBar/NashHPBarPlugin/NashHPBarPlugin.zsc"
#include "zscript_libraries/NashHPBar/NashHPBarHandler/NashHPBarHandler.zsc"

//damnums
#include "zscript_libraries/damnums/constants.txt"
#include "zscript_libraries/damnums/damnum.txt"
#include "zscript_libraries/damnums/events.txt"
#include "zscript_libraries/damnums/fonts/base.txt"
#include "zscript_libraries/damnums/fonts/borderlands.txt"
#include "zscript_libraries/damnums/fonts/gamedefaults.txt"