//zscript_DI/items/debuffs/motionblur.zsc

Class DI_QuestDebuff_MotionBlur : DI_QuestDebuff
{
	default 
	{
		Tag "\cgCurse (Motion Blur)";
	}
	override double GiveAccuracy() 
	{
		if (!plr) {return 0.0;}
        double v1 = plr.Vel.X * 0.5;
        if (v1 < 0) {v1 *= -1;}
        double v2 = plr.Vel.Y * 0.5;
        if (v2 < 0) {v2 *= -1;}
        double v3 = plr.Vel.Z * 0.5;
        if (v3 < 0) {v3 *= -1;}
        return 0.6 * (v1 + v2 + v3);
	}
}