//zscript_DI/items/passives/freshbonusgiver.zsc

Class DI_FreshBonusGiver : DIPassiveInventory
{
	Default
	{
		Tag "Fresh Bonus +";
		Inventory.Icon "POWRC0";
		Inventory.PickupMessage "Freshness Increased! (+1 coin per Fresh Weapon Bonus)";
		Inventory.MaxAmount 3;
	}
	
	override int GiveFreshBonus()
	{
		if (!wpn || !plr) {return 0;}
		return amount;
	}
	
	States
	{
		Spawn:
			POWR C -1;
			Stop;
	}
}