//zscript_DI/items/passives/gunslinger.zsc

Class DI_Gunslinger : DIPassiveInventory
{
	Default
	{
		Tag "Gunslinger";
		Inventory.Icon "POWRK0";
		Inventory.PickupMessage "Gunslinger Acquired! (Gain +1 DMG for every weapon you own.)";
		Inventory.MaxAmount 3;
	}
	
	override int GiveBaseDamage()
	{
		if (!plr) {return 0;}
		return 10 * plr.weaponnum * plr.CountInv(GetClassName());
	}
	
	States
	{
		Spawn:
			POWR K -1;
			Stop;
	}
}