//zscript_DI/items/event/speedrun.zsc

Class DI_Speedrun : DIPassiveInventory
{
    default 
	{
		DIPassiveInventory.DIHidden true;
	}
	
	override double GivePlayerSpeed()
	{
		if (!plr) {return 0.0;}
		return 0.3;
	}
	
	override double GiveWeaponSpeed()
	{
		if (!plr) {return 0.0;}
		return -0.3;
	}

    override string, int GiveEnemyItem()
    {
        if (owner) {return "DI_SpeedyFoes_Buff", 2;}
        else return "", 0;
    }
}