//zscript_DI/shop/ghostshop.zsc

//this is not a shop. this is used to show which shops will appear on the next shop upgrade.

class DI_GhostShop : DI_Actor
{	
	Default
	{
		RenderStyle "Translucent";
		Radius 20;
		Height 96;
		+VISIBILITYPULSE;
		-SOLID;
		//$Category "DI/Shops/"
		//$Title "Ghost Shop (Decor)"
		//$Color 4
	}
	
	States
	{
		Spawn:
			SHOP Z -1;
			Stop;
	}
}

class DI_GhostChest : DI_GhostShop
{
	States
	{
		Spawn:
			SHOP Y -1;
			Stop;
	}
}