//zscript_DI/items/consumables/reroll.zsc

Class DI_Dice : DIConsumable
{
	Default
	{
		Tag "Instant Reroll";
		DIConsumable.CooldownTics 15;
		DIConsumable.BlockInWave true;
		Inventory.MaxAmount 3;
		Inventory.Icon "DICEA0";
		Inventory.PickupMessage "Got an instant reroll! Use while in the shop to reroll all shop items.";
	}
	
	override bool DIUse(bool pickup)
	{
		EventHandler.SendNetworkEvent("DIRerollShops");
		return true;
	}
	
	States
	{
		Spawn:
			DICE A -1;
			Stop;
	}
}